[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fitz>=0.0.1.dev2",
    "nltk>=3.9.1",
    "numpy>=2.3.1",
    "pymupdf>=1.26.3",
    "scikit-learn>=1.7.1",
]
